services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NITRO_PRESET=node-server
    container_name: nuxt-app
    restart: always
    environment:
      - YOUR_ENV_KEY=${YOUR_ENV_KEY}
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/hello" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
