services:
  canvas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canvas
    restart: always
    environment:
      - NUXT_PRIVATE_RESEND_API_KEY=${NUXT_PRIVATE_RESEND_API_KEY}
      - NUXT_PUBLIC_AVAILABLE=${NUXT_PUBLIC_AVAILABLE}
      - NUXT_PUBLIC_STUDIO_TOKENS=${NUXT_PUBLIC_STUDIO_TOKENS}
      - NUXT_PUBLIC_MEETING_LINK=${NUXT_PUBLIC_MEETING_LINK}
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/hello" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
