export const tags = [
  "web",
  "developer",
  "portfolio",
  "hugo",
  "richard",
  "hugo richard",
  "hrfolio",
  "hr",
  "folio",
  "hr folio",
  "Nice",
  "France",
  "Nice France",
  "Côte d'Azur",
  "Cote d'Azur",
  "Côte d'Azur France",
  "Cote d'Azur France",
  "art",
  "design",
  "designer",
  "art director",
  "directeur artistique",
  "Développeur",
];
