name: "💬 Question"
description: Ask a question about the project.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a question, please make sure that you have read existing [issues](https://github.com/HugoRCD/canvas/issues) to see if the feature has already been requested or implemented. If it has, please add your reaction to the existing issue instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
